#ifndef DEFINES_H
#define DEFINES_H

#define SAVE_FILENAME "highscore.txt"
#define DEFAULT_SPEED 700

#define PLAYING_FIELD_WIDTH 10
#define PLAYING_FIELD_HEIGHT 20

#define DRAW_FIELD_X 1
#define DRAW_FIELD_Y 1

#define PLAYING_FIELD_X (DRAW_FIELD_X + 1)
#define PLAYING_FIELD_Y (DRAW_FIELD_Y + 1)

#define PLAYING_FIELD_COLOR COLOR_WHITE
#define PLAYING_FIELD_FRAME_CHAR '#'
#define FIGURES_CHAR '0'

#define FIGURE_SPAWN_X (PLAYING_FIELD_WIDTH / 2)
#define FIGURE_SPAWN_Y 0

#define START_TEXT_X (DRAW_FIELD_X + PLAYING_FIELD_WIDTH + 3)
#define START_TEXT_Y (PLAYING_FIELD_HEIGHT / 2 + DRAW_FIELD_Y - 1)

#define FIGURES_COUNT 7

#define NEXT_FIGURE_X START_TEXT_X
#define NEXT_FIGURE_Y (DRAW_FIELD_Y + 1)
#define NEXT_FIGURE_IMAGE_X NEXT_FIGURE_X
#define NEXT_FIGURE_IMAGE_Y (NEXT_FIGURE_Y + 1)

#define SCORE_X START_TEXT_X
#define SCORE_Y (NEXT_FIGURE_IMAGE_Y + 3)
#define SCORE_NUMBER_X SCORE_X
#define SCORE_NUMBER_Y (SCORE_Y + 1)

#define HIGHSCORE_X START_TEXT_X
#define HIGHSCORE_Y (SCORE_NUMBER_Y + 2)
#define HIGHSCORE_NUMBER_X HIGHSCORE_X
#define HIGHSCORE_NUMBER_Y (HIGHSCORE_Y + 1)

#define LEVEL_X START_TEXT_X
#define LEVEL_Y (HIGHSCORE_NUMBER_Y + 2)
#define LEVEL_NUMBER_X LEVEL_X
#define LEVEL_NUMBER_Y (LEVEL_Y + 1)

#define PAUSED_TEXT "PAUSED"
#define PAUSED_X \
  ((PLAYING_FIELD_X + PLAYING_FIELD_WIDTH / 2) - (strlen(PAUSED_TEXT) / 2))
#define PAUSED_Y (PLAYING_FIELD_Y + PLAYING_FIELD_HEIGHT / 2 - 1)

#endif
